### PR TITLE
Proxy Adapter

### PR DESCRIPTION
**Pull request by ANeaves**
Proxy Adapter for Odin Control.

Designed so that one Odin Control node can be linked to adapters in other nodes, accessing them as if they were a part of the local Parameter Tree structure.

### CODE REVIEW

**Comment by timcnicholls** [comment]
@ANeaves I've pushed a commit to this PR removing the SystemStatus adapter test config, which a) makes no sense prior to the PR of the SystemStatus adapter, and b) was an accidental commit by me containing config specific to my Mac

**Comment by ajgdls** [comment]
I'm excited to try this out.  I will setup statistics odin-control servers on 2 different Excalibur servers and pull back all of the information through our EPICS application.

**Comment by ANeaves** [comment]
@ajgdls Any luck testing this with your excalibur servers? I'd be interested to hear how it works in a more realistic setting

**Comment by ajgdls** [comment]
Hi @ANeaves sorry not yet.  I will set it up today/tomorrow.

**Comment by ajgdls** [comment]
p.s. I forgot to say it is awesome as well !

**Comment by timcnicholls** [comment]
Thanks @ajgdls . On issue 1) the whitespace thing can be fixed easily. It strips leading/trailing whitespace when splitting into targets (i.e. on comma) but not when splitting target=URL on each target. Is that the basis of it being too restrictive, or did you mean that config syntax is limiting anyway?

**Comment by timcnicholls** [comment]
BTW, the 'node_1=' target name is arbitrary :wink:

**Comment by ajgdls** [comment]
@timcnicholls I only referred to the whitespace.  It was simply that the error didn't make it clear what the problem was and so being able to cope with the whitespace would make it much easier to use.  I didn't see any other problems and being able to label the nodes as anything is also good.

**Comment by timcnicholls** [comment]
@ajgdls Great, that's easy to fix then. When I wrote that bit of config parsing I found myself wishing for JSON or YAML. INI-style config isn't particularly expressive for lists of parameters...

**Comment by ANeaves** [comment]
Hey @ajgdls, I'm struggling to replicate the issue you are getting with the doubling up response. Which adapter is it that you are using as the proxy target?

**Comment by ajgdls** [comment]
Hi, I'm pointing it at the statistics adapter running on a separate machine.  I'll re-check my test to ensure I'm not doing something silly in the output.  I could demo it to you this afternoon...

**Comment by ajgdls** [comment]
Proxy config file:

```
[server]
debug_mode = 1
http_port  = 8888
http_addr  = 0.0.0.0
adapters   = proxy

[tornado]
logging = error

[adapter.proxy]
module = odin.adapters.proxy.ProxyAdapter
targets = 
  node_1=http://pc0054.cs.diamond.ac.uk:8888/api/0.1/stats/
request_timeout = 2.0
```

System status config file:
```
[server]
debug_mode = 1
http_port  = 8888
http_addr  = 0.0.0.0
adapters   = stats

[tornado]
logging = error

[adapter.stats]
module = odin.adapters.system_status.SystemStatusAdapter
disks = /home/gnx91527
interfaces = enp0s25
processes = stFrameProcessor1.sh, stFrameReceiver1.sh
```

**Comment by ANeaves** [comment]
Source of the error has been discovered! Once again we have trouble due to the terror of **TRAILING SLASHES**. If you make the request for the stats status without a slash on the end it works fine. Time to fix

**Comment by timcnicholls** [comment]
🤦‍♂️

**Comment by timcnicholls** [comment]
Nice job @ANeaves . No longer :turtle::turtle::turtle: all the way down :wink:

**Comment by ANeaves** [comment]
@ulrikpedersen @GDYendell @MattTaylorDLS You guys happy for me to merge this?

**Pull request merged**
