### PR TITLE
Added adapter to monitor server disk, network and process statistics.

### PR DESCRIPTION
**Pull request by ajgdls**
Updated to make use of the ParameterTree class present in odin-control.  @timcnicholls are you able to test this out before accepting as I would like to check it works for you as expected.  Example config file section is present in the comments at the top of the file.

### CODE REVIEW

**Comment by timcnicholls** [comment]
- Works fine under python 2.7 and 3.6 👍 
- Puts a serious dent in my code coverage stats as there are no unit tests :grimacing: \*coughs\*
- Would also be good to have an example config file, q.v. odin/testing/config/test_system_info.cfg
- If I give it a nonsense NIC, it continues without errors but displays empty status for that NIC:
```
    "network": {
        "em1": {
            "bytes_recv": 0,
            "bytes_sent": 0,
            "dropin": 0,
            "dropout": 0,
            "errin": 0,
            "errout": 0,
            "packets_recv": 0,
            "packets_sent": 0
        },

```
- Ditto for nonsense process names:
```
        "process": {
             "mythical": {
                "cpu_affinity": [],
                "cpu_percent": 0.0,
                "memory_percent": 0.0,
                "memory_rss": 0,
                "memory_shared": 0,
                "memory_vms": 0
            },
```
- If I give it an incorrect disk name, the update loops throws unhandled exceptions:
```
[E 180710 15:26:33 system_status:244] [Errno 2] No such file or directory: '/random'
    Traceback (most recent call last):
      File "/u/tcn45/develop/projects/odin-control/odin/adapters/system_status.py", line 237, in monitor_disks
        usage = psutil.disk_usage(disk)
      File "/u/tcn45/.virtualenvs/odin-control-2.7/lib/python2.7/site-packages/psutil-5.4.6-py2.7-linux-x86_64.egg/psutil/__init__.py", line 1966, in disk_usage
        return _psplatform.disk_usage(path)
      File "/u/tcn45/.virtualenvs/odin-control-2.7/lib/python2.7/site-packages/psutil-5.4.6-py2.7-linux-x86_64.egg/psutil/_psposix.py", line 133, in disk_usage
        st = os.statvfs(path)
    OSError: [Errno 2] No such file or directory: '/random'
```
- Just FYI - on MacOS where monitoring processes requires sudo privileges, the adapter throws an unhandled exception at startup and kills the process:
```
[I 180710 15:43:52 server:65] Using the 0MQ IOLoop instance
[D 180710 15:43:52 system_status:224] Adding process iTerm2 to monitor list
Traceback (most recent call last):
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/_psosx.py", line 348, in catch_zombie
    yield
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tcn/.virtualenvs/odin-control-3.6/bin/odin_server", line 11, in <module>
    load_entry_point('odin', 'console_scripts', 'odin_server')()
  File "/Users/tcn/Develop/projects/odin-control/odin/server.py", line 69, in main
    config.static_path, adapters)
  File "/Users/tcn/Develop/projects/odin-control/odin/http/server.py", line 50, in __init__
    self.api_route.register_adapter(adapters[adapter])
  File "/Users/tcn/Develop/projects/odin-control/odin/http/routes/api.py", line 218, in register_adapter
    self.adapters[adapter_config.name] = adapter_class(**adapter_config.options())
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 47, in __init__
    self.system_status = SystemStatus(None, **kwargs)
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 119, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 179, in __init__
    self.add_process(process.strip())
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 225, in add_process
    self._processes[process_name] = self.find_process(process_name)
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 290, in find_process
    parent = self.find_process_by_name(process_name)
  File "/Users/tcn/Develop/projects/odin-control/odin/adapters/system_status.py", line 309, in find_process_by_name
    for cmdline in p.cmdline():
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/__init__.py", line 661, in cmdline
    return self._proc.cmdline()
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/_psosx.py", line 330, in wrapper
    return fun(self, *args, **kwargs)
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/_psosx.py", line 412, in cmdline
    return cext.proc_cmdline(self.pid)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/tcn/.virtualenvs/odin-control-3.6/lib/python3.6/site-packages/psutil-5.4.6-py3.6-macosx-10.13-x86_64.egg/psutil/_psosx.py", line 361, in catch_zombie
    raise AccessDenied(proc.pid, proc._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=1, name='launchd')
```
While you cant fix the privs requirement, it would be good to trap exceptions during adapter initialisation.

**Comment by ajgdls** [comment]
Ah OK yes I can add some unit tests, sorry, and trap exceptions during the monitor and init.

I should be able to catch the bad NIC and process by putting None into the values. For the nonsense NIC would I be able to eject it completely from the parameter tree? (Does parameter tree support deleting?)
For the process I think it is not so simple as it is perfectly valid to run this up without the monitored processes executing at that time so I think setting values to None indicates that the process is not currently live, what do you think?

**Comment by timcnicholls** [comment]
Sounds sensible re the processes. Have to say I've never tried removing an element from the ParameterTree so we'll have to try it! You could validate the NIC names at startup and only build them into the tree if present?

**Comment by ajgdls** [comment]
Hi @timcnicholls I've just discovered the ParameterTree will not let me change the type of a parameter once it has already been set, which means that None values cannot currently be used.
Do you think it is valid for the ParameterTree to check types apart from the None case?  None is a bit special in that it can be used to represent uninitialised values.
I'm assuming the ParameterTree is used elsewhere so I wouldn't make that change unless you agree to it.

**Comment by timcnicholls** [comment]
@ajgdls I think you can avoid this problem if you use the ParameterAccessor paradigm in ParameterTree, i.e instead of defining an dict structure with 'None' in leaf nodes, you use the (getter, setter) tuple initialiser, rather like the SystemInfo adapter does for server_uptime. Try that and see if it works for you. Otherwise we can treat None as a special case as you describe.

**Comment by ajgdls** [comment]
I had a look into it but unfortunately the callback isn't passed any parameter to know which item initiated it and so I would need to be passing specific object instance methods as callbacks for each process.  Also it would trigger the lookup of a dead process when someone performs a get...
I'll commit the change to the tree but if you think I've missed something simpler I can back it out again.

**Comment by timcnicholls** [comment]
HI @ajgdls just noticed this open PR from last July... Where did we get to with this?

**Comment by ajgdls** [comment]
Hi @timcnicholls I think it was fairly complete.  I guess you might want to test it on MacOS to be sure it works correctly?
I think this got shelved until we had the proxy adapter available.

**Comment by timcnicholls** [comment]
Closing this PR in favour of updated #31 from local feature branch

**Pull request closed without merging**
